on: pull_request
name: Terraform
jobs:
  filter-to-pr-open-synced:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: terraform-fmt
      uses: hashicorp/terraform-github-actions/fmt@v0.4.6
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TF_ACTION_WORKING_DIR: .
    # - name: terraform-init
    #   uses: hashicorp/terraform-github-actions/init@v0.4.6
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     TF_ACTION_WORKING_DIR: .
    # - name: terraform-validate
    #   uses: hashicorp/terraform-github-actions/validate@v0.4.6
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     TF_ACTION_WORKING_DIR: .
